version: 3.3

services:
  app:
    image: szark/udacity-proj4
    ports:
      - "8080:80"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 200M
          cpu: 1
        reservations:
          memory: 50M
          cpu: 100m