apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  namespace: capstone-ns 
  labels:
    app: capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: $dockerpath
        ports:
        - containerPort: 5000
        volumeMount:
        - name: webapp-cm
          mountPath: /app/templates
      volumes:
        - name: webapp-cm
          configMap:
            name: webapp-cm
