Description: >
  Minikube

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub Minikube
      GroupDescription: Allow port 22 and port 8080
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.small
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: minikube_oregon
      #ImageId: ami-0cc158853935719b7
      ImageId: ami-0438cf1f8a8765051
      Tags:
        - Key: app
          Value: minikube