---
- name: Creates web directory
  become_user: ubuntu
  become: yes
  file:
    path: /home/ubuntu/app
    state: directory

- name: Unarchive
  become_user: ubuntu
  become: yes 
  unarchive: 
    src: ~/project.tar
    dest: /home/ubuntu/app

- name: Create k8s namespace
  become_user: ubuntu
  become: yes
  community.kubernetes.k8s:
    name: capstone-ns
    api_version: v1
    kind: namespace
    state: present

- name: Update config map
  become_user: ubuntu
  become: yes
  shell: |
    kubectl apply -k /home/ubuntu/app/project/templates/ -n capstone-ns 
    kubectl delete pod -l app=capstone

- name: Create deployment
  become_user: ubuntu
  become: yes
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: capstone
        namespace: capstone-ns 
        labels:
          app: capstone
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: capstone
        template:
          metadata:
            labels:
              app: capstone
          spec:
            containers:
            - name: capstone
              image: szark/udacity-capstone
              ports:
              - containerPort: 5000
              volumeMounts:
              - name: webapp-cm
                mountPath: /app/templates
              imagePullPolicy: Always
            volumes:
              - name: webapp-cm
                configMap:
                  name: webapp-cm

- name: Run port forward 
  become_user: ubuntu
  become: yes
  shell: |
    pgrep kubectl
    if [ $? -eq 0 ]
    then
      pkill kubectl
      sleep 5
      until kubectl get pods -n capstone-ns | grep Running; do sleep 5; done
      nohup kubectl port-forward -n capstone-ns deployment/capstone --address 0.0.0.0 8080:5000 </dev/null >/dev/null 2>&1 &
    else
      until kubectl get pods -n capstone-ns | grep Running; do sleep 5; done
      nohup kubectl port-forward -n capstone-ns deployment/capstone --address 0.0.0.0 8080:5000& </dev/null >/dev/null 2>&1 &
    fi