---
- name: Creates web directory
  become_user: ubuntu
  become: yes
  file:
    path: /home/ubuntu/app
    state: directory

- name: Unarchive
  become_user: ubuntu
  become: yes 
  unarchive: 
    src: ~/project.tar
    dest: /home/ubuntu/app

- name: Create k8s namespace
  become_user: ubuntu
  become: yes
  community.kubernetes.k8s:
    name: capstone-ns
    api_version: v1
    kind: namespace
    state: present

